# Generated by Django 3.0.3 on 2020-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('profession', models.CharField(choices=[('Student', 'student'), ('Housewife', 'housewife'), ('Businessman', 'businessman'), ('other', 'other')], max_length=12, verbose_name='Profession')),
                ('degree', models.CharField(choices=[('POST GRADUATE', 'postgraduate'), ('GRADUATE', 'graduate'), ('10th pass', '10thpass'), ('12th pass', '12thpass')], max_length=18, verbose_name='Degree')),
                ('state', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('profile_img', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
    ]
