# Generated by Django 3.0.3 on 2020-04-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='This is my bio'),
            preserve_default=False,
        ),
    ]
