# Generated by Django 3.0.3 on 2020-04-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200426_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(default='VJTI', max_length=50),
            preserve_default=False,
        ),
    ]
