# Generated by Django 3.0.3 on 2020-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20200412_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
