# Generated by Django 3.0.3 on 2020-04-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20200412_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursename',
            field=models.CharField(max_length=50),
        ),
    ]
