# Generated by Django 3.0.3 on 2020-04-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20200426_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
