# Generated by Django 3.0.3 on 2020-04-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_auto_20200426_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='code',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
